# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/api2r/pkgskills-ci:release
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - uses: api2r/actions/install@v1
        with:
          use-container: "true"
          token: ${{ secrets.GITHUB_TOKEN }}
          needs: website
          extra-packages: any::pkgdown gilead-biostats/qcthat local::. any::glue

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy PR preview 🧪
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
          target-folder: pr/${{ github.event.number }}

      - name: Comment with PR site URL 🌐
        if: github.event_name == 'pull_request'
        run: |
          intPRNumber <- ${{ github.event.pull_request.number }}
          strOwner <- tolower(qcthat::GetGHOwner())
          strRepo <- qcthat::GetGHRepo()
          strURL <- glue::glue(
            "https://{strOwner}.github.io/{strRepo}/pr/{intPRNumber}"
          )
          print(paste("🌐 URL:", strURL))
          qcthat::CommentIssue(
            intPRNumber,
            glue::glue("🌐 [PR pkgdown deployed]({strURL})"),
            NULL
          )
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
